#!/bin/bash

if [ ! -f "/opt/installed" ]; then
  chmod 555 /bin/restore_or
  chmod 555 /bin/install_orfs

  echo ECE 260C Image II: Source-Editable
  echo Preparing to start for the first time...
  echo
  
  #echo "1/3 Restoring OpenROAD Sources..."
  #restore_or
  
  #echo "2/3 Installing OpenROAD Binaries..."
  #cd /OpenROAD/build
  #make -j install 1> /dev/null
  cd /

  echo "1/1 Installing OpenROAD-flow-scripts.."
  install_orfs

  touch /opt/installed
  echo "Done."
  echo

fi

export PATH="/opt/oss-cad-suite/bin":$PATH
export YOSYS_EXE=/opt/oss-cad-suite/bin/yosys
export OPENROAD_EXE=/OpenROAD/build/src/openroad

cat /etc/motd