#!/bin/bash

if [ ! -f "/opt/installed" ]; then
  chmod 555 $(which restore_or)
  chmod 555 $(which install_orfs)

  echo ECE 260C Image II: Source-Editable
  echo Preparing to start for the first time...
  echo
  
  echo "1/4 Restoring OpenROAD Sources..."
  restore_or
  
  echo "2/4 Installing OpenROAD Binaries..."
  cd /OpenROAD/build
  make -j install 1> /dev/null
  cd /

  echo "3/4 Installing OpenROAD-flow-scripts.."
  install_orfs

  echo "4/4 Finalizing..."
  touch /opt/installed
  echo "Done."
  echo

fi

export PATH="/opt/oss-cad-suite/bin":$PATH
export YOSYS_EXE=/opt/oss-cad-suite/bin/yosys

cat /etc/motd