FROM ubuntu:22.04 AS base

SHELL ["/bin/bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles

COPY image_init.sh /opt
RUN source /opt/image_init.sh
COPY prep_or.sh /opt
RUN source /opt/prep_or.sh

COPY restore_or /bin
COPY install_orfs /bin
COPY bashrc /root/.bashrc
RUN chmod 777 /root/.bashrc

COPY motd.txt /etc/motd

FROM scratch

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles
COPY --from=base / /
CMD ["/bin/bash"]
SHELL ["/bin/bash", "-c"]