FROM ubuntu:22.04

SHELL ["/bin/bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles

COPY openroad.deb /opt
COPY image_init.sh /opt
RUN source /opt/image_init.sh

COPY orfs_copy /bin
COPY image_finalize.sh /opt
RUN source /opt/image_finalize.sh

COPY motd.txt /etc/motd