FROM ubuntu:24.04 AS base

SHELL ["/bin/bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles

COPY image_init.sh /opt
RUN source /opt/image_init.sh
COPY prep_or_dep.sh /opt
RUN source /opt/prep_or_dep.sh
COPY prep_or.sh /opt
RUN source /opt/prep_or.sh
COPY prep_gui.sh /opt
RUN source /opt/prep_gui.sh

COPY bashrc /root/.bashrc
RUN chmod 777 /root/.bashrc

COPY motd.txt /etc/motd

RUN apt update && apt install -y tigervnc-standalone-server mwm btop xfce4 xfce4-terminal

RUN apt-get update && \
    apt-get install -y locales && \
    locale-gen en_US.UTF-8 && \
    dpkg-reconfigure locales

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8